server:
  port:8080

#自定义图片存储目录
web.upload-path: C:/whut/

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/air_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#  jpa:
#    database: MySQL
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  jackson:
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #模板引擎配置

  thymeleaf:
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

  #配置静态资源
  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.example.demo.entity

#logging:
#  pattern:
#    console: '%d{yyyy‐MM‐dd}[%thread]%‐5level%logger{50}‐%msg%n'
#  level:
#    com.example.demo.controller: info


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
